#!/bin/sh

OUTDIR="/home/linuxcnc/linuxcnc/pics"
CAMURL="http://admin:NHxdZ5iZA36pAFv@192.168.2.12/ISAPI/Streaming/channels/101/picture"

if [ -z "$1" ]; then
  echo "usage: M106 <pic-no>"
  exit 1
fi

PICNO=`echo "$1" | cut -d '.' -f 1`

wget --output-document="$OUTDIR/$PICNO.jpg" "$CAMURL"

