
COMP = halcompile --compile --userspace

all: M100 M101 M102 M103 M104 M105

clean:
	rm -f M1[0-9][0-9] *.o

M100: M100.c
	$(COMP) $<

M101: M101.c
	$(COMP) $<

M102: M102.c
	$(COMP) $<

M103: M103.c
	$(COMP) $<

M104: M104.c
	$(COMP) $<

M105: M105.c
	$(COMP) $<

